name: sitemon
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  geolocator: ^14.0.2
  local_auth: ^2.1.6
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  pdf: ^3.10.8
  path_provider: ^2.1.5
  syncfusion_flutter_pdf: ^30.1.37
  http: ^1.3.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.3.2
  intl: ^0.20.2
  flutter_pdfview: ^1.2.0
  open_filex: ^4.3.2
  dio: ^5.4.3+1
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  rename: ^3.1.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/